name: 'Setup git-chglog environment'
description: 'Setup a git-chglog environment and add it to the PATH'
author: 'GitHub'
inputs:
  git-chglog-version:
    required: false
    description: 'The git-chglog version to download (if necessary) and use. Supports semver spec and ranges.'
  token:
    required: false
    description: Used to pull node distributions from git-chglog-versions.  Since there's a default, this is typically not supplied by the user.
    default: ${{ github.token }}
runs:
  using: 'node12'
  main: 'dist/index.js'
